### ISSUE TITLE
How does PSA work?

### ISSUE THREAD

**Issue by lv2020** [qiaolian9/Pruner#1]
Thank you for your recent code release. While attempting to replicate your results, I encountered some issues that need clarification.

In "try_Pruner_on_NvidiaA100.md," there's a mention of "register device abstraction" in "task_scheduler.py." Could you explain how this works? The documentation mentions a dictionary for hardware and parameters, but I'm unclear on its functionality.

Additionally, I think there should be some modifications in "task_scheduler.py" for calculating total latency. But I can't find it, do I miss anything?

Any help would be appreciated.

**Comment by qiaolian9** [comment]
We apologize for any inconvenience caused. You can access the code via the provided URL(https://github.com/AnonymousICML24/Pruner), which contains the cross-platform pre-trained model(for MTL). Following the tutorial, you can test the tuning process. Thanks for  raising any questions about the code.

**Comment by lv2020** [comment]
Thanks for your quick response!
